name: Docker Build Service

on:
  push:
     branches: [ $default-branch ]
  pull_request: 

jobs:
  build:
    uses: fasttrack-solutions/ci/.github/workflows/docker-service.yml@main
    with:
      image: ${{ github.event.repository.name }}
      dockerfile: "./deployments/docker/Dockerfile"
    secrets: inherit    